# Generated by Django 5.0.4 on 2024-05-10 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=90, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[('Object Oriented Programming', 'Object Oriented Programming'), ('Web Programming', 'Web Programming'), ('Discrete Mathematics', 'Discrete Mathematics'), ('Calculus 1', 'Calculus 1'), ('Calculus 2', 'Calculus 2')], max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('instructor', models.CharField(max_length=100, null=True)),
                ('scheduled', models.IntegerField(null=True)),
                ('prerequisites', models.CharField(max_length=200, null=True)),
                ('capacity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=250, null=True, unique=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('STT', 'Sunday, Tuesday, Thursday'), ('MW', 'Monday, Wednesday')], max_length=50, null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('room_no', models.CharField(max_length=10, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.student')),
            ],
        ),
    ]
