# Generated by Django 5.0.4 on 2024-05-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(choices=[('Object Oriented Programming', 'Object Oriented Programming'), ('Web Programming', 'Web Programming'), ('Discrete Mathematics', 'Discrete Mathematics'), ('Calculus 1', 'Calculus 1'), ('Calculus 2', 'Calculus 2'), ('  ', '  ')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='days',
            field=models.CharField(choices=[('S,T,T', 'Sunday, Tuesday, Thursday'), ('M,W', 'Monday, Wednesday')], max_length=50, null=True),
        ),
    ]
