# Generated by Django 5.0.4 on 2024-05-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_prerequisites_alter_courseschedule_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
