# Generated by Django 5.0.4 on 2024-05-22 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_courseschedule_course_remove_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(choices=[('Object Oriented Programming', 'Object Oriented Programming'), ('Web Programming', 'Web Programming'), ('Discrete Mathematics', 'Discrete Mathematics'), ('Calculus 1', 'Calculus 1'), ('Calculus 2', 'Calculus 2'), ('', ''), ('Data Structure', 'Data Structure'), ('Computer Programming', 'Computer Programming')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='scheduled',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.courseschedule'),
        ),
    ]
