# Generated by Django 5.0.4 on 2024-05-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='courses.course'),
        ),
    ]
