# Generated by Django 5.0.4 on 2024-05-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_courseschedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
