# Generated by Django 5.0.4 on 2024-05-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_courseschedule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
