# Generated by Django 5.0.4 on 2024-05-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_studentregistration_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('Object Oriented Programming', 'Object Oriented Programming'), ('Web Programming', 'Web Programming'), ('Discrete Mathematics', 'Discrete Mathematics'), ('Calculus 1', 'Calculus 1'), ('Calculus 2', 'Calculus 2'), ('Calculus 3', 'Calculus 3'), ('Computer Programming', 'Computer Programming'), ('Data Structure', 'Data Structure')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(blank=True, choices=[('Object Oriented Programming', 'Object Oriented Programming'), ('Web Programming', 'Web Programming'), ('Discrete Mathematics', 'Discrete Mathematics'), ('Calculus 1', 'Calculus 1'), ('Calculus 2', 'Calculus 2'), ('Calculus 3', 'Calculus 3'), ('', ''), ('Data Structure', 'Data Structure'), ('Computer Programming', 'Computer Programming')], max_length=200, null=True),
        ),
    ]
