# Generated by Django 5.0.4 on 2024-05-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_name_alter_course_prerequisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='completed',
        ),
    ]
